name: Fetch Assets
on:
  schedule:
    - cron: "0 12 * * 4"
  workflow_dispatch:

jobs:
  info:
    name: Update Pico covers 
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Get Pico info
        run: yarn run pico:info

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pico-info
          path: pico/info
          retention-days: 1

  covers:
    name: Update Pico covers 
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Get Pico covers
        run: yarn run pico:covers

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pico-covers
          path: pico/covers
          retention-days: 1
          
  icons:
    name: Update Pico icons 
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Get Pico icons
        run: yarn run pico:icons

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pico-icons
          path: pico/icons
          retention-days: 1

  commit:
    name: Commit changes 
    runs-on: ubuntu-latest
    needs:
      - info
      - covers
      - icons
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Download Pico info artifact
        uses: actions/download-artifact@v2
        with:
          name: pico-info

      - name: Download Pico covers artifact
        uses: actions/download-artifact@v2
        with:
          name: pico-covers

      - name: Download Pico icons artifact
        uses: actions/download-artifact@v2
        with:
          name: pico-icons

      - name: "Commit changes"
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
