name: Fetch Assets
on:
- workflow_dispatch 

jobs:
  assets:
    name: Update Assets 
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Get Pico info & cover images
        run: yarn run pico:main
      - name: Get Pico icons
        run: yarn run pico:icons
      - name: "Commit changes"
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
